options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci-5409-s23/k8s-assignment/container-2:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci-5409-s23/k8s-assignment/container-2:$SHORT_SHA'
      - '.'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/csci-5409-s23/k8s-assignment/container-2:latest'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/csci-5409-s23/k8s-assignment/container-2:$SHORT_SHA'
      

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-assignment-gke'
    args:
      - 'set'
      - 'image'
      - 'deployment/k8s-assignment-deployment'
      - 'container-2=us-central1-docker.pkg.dev/csci-5409-s23/k8s-assignment/container-2:$SHORT_SHA'
  
